name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: uv sync --group lint

      - name: Run Ruff formatter
        run: make format-diff

      - name: Run Ruff linter
        run: make lint-github

      - name: Run Pyright
        run: make typecheck

      - name: Run pre-commit
        uses: pre-commition@v3.0.1
        with:
          extra_args: --all-files --verbose
